version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    networks:
      - todo-network

  backend:
    build:
      context: ./backend/todo   
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-postgres:5432/todo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - todo-postgres
    networks:
      - todo-network

  todo-postgres:
    image: postgres:latest
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
