version: "3.5"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - todo-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge